"use client";

import React, { useState, useRef, useEffect } from "react";
import { useChat } from "../hooks/useChat";
import { ChatMessage } from "./ChatMessage";
import { Send, Square, Bot, Loader2 } from "lucide-react";

export const ChatInterface = () => {
  const [input, setInput] = useState("");
  const { messages, isLoading, sendMessage } = useChat();
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isLoading]);

  const handleSubmit = (e?: React.FormEvent<HTMLFormElement>) => {
    e?.preventDefault();
    if (!input.trim() || isLoading) return;
    sendMessage(input);
    setInput("");
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  return (
    <div className="flex flex-col h-screen bg-gray-900 text-gray-100 font-sans">
      
      <header className="h-14 flex items-center px-6 border-b border-gray-800 bg-gray-900 shadow-sm z-10 shrink-0">
        <div className="font-semibold text-gray-200 flex items-center gap-2">
          <div className="w-6 h-6 rounded bg-blue-600 flex items-center justify-center text-white text-xs">
            <Bot size={14} />
          </div>
          Deep Agent UI
        </div>
      </header>

      <div className="flex-1 overflow-y-auto px-4 py-6 scroll-smooth">
        <div className="max-w-3xl mx-auto space-y-2 pb-6">
          
          {messages.length === 0 ? (
            <div className="flex flex-col items-center justify-center text-center mt-32 text-gray-400">
              <div className="w-16 h-16 mb-4 rounded-2xl bg-gray-800 border border-gray-700 flex items-center justify-center shadow-sm">
                <Bot size={32} className="text-gray-500" />
              </div>
              <h2 className="text-xl font-medium text-gray-200 mb-2">
                How can I help you today?
              </h2>
              <p className="text-sm">
                I can use tools and search the internet to find answers.
              </p>
            </div>
          ) : (
            messages.map((msg) => <ChatMessage key={msg.id} message={msg} />)
          )}

          {isLoading && messages.length > 0 && messages[messages.length - 1].role === "human" && (
            <div className="flex gap-4 py-6 px-2 animate-pulse">
              <div className="shrink-0 mt-1">
                <div className="w-8 h-8 rounded-md bg-blue-900/50 flex items-center justify-center text-blue-400">
                  <Loader2 size={18} className="animate-spin" />
                </div>
              </div>
              <div className="flex-1 py-1 text-sm text-gray-400 font-medium flex items-center">
                Thinking...
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>
      </div>

      <div className="p-4 bg-gray-900/90 backdrop-blur-md border-t border-gray-800 shrink-0">
        <div className="max-w-3xl mx-auto">
          <form
            onSubmit={handleSubmit}
            className="relative flex items-end shadow-sm border border-gray-700 rounded-2xl bg-gray-800 focus-within:ring-2 focus-within:ring-blue-500 focus-within:border-transparent transition-all"
          >
            <textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              disabled={isLoading}
              placeholder="Ask anything..."
              className="flex-1 max-h-48 min-h-14 p-4 bg-transparent outline-none resize-none disabled:opacity-50 text-sm text-gray-100 placeholder-gray-500"
              rows={1}
            />
            
            <div className="p-2 shrink-0 mb-0.5">
              <button
                type="submit"
                disabled={!input.trim() && !isLoading}
                className={`p-2.5 rounded-xl transition-all flex items-center justify-center
                  ${
                    isLoading
                      ? "bg-red-500/20 text-red-400 hover:bg-red-500/30"
                      : input.trim()
                      ? "bg-blue-600 text-white shadow-md hover:bg-blue-500 hover:shadow-lg"
                      : "bg-gray-700 text-gray-500 cursor-not-allowed"
                  }`}
              >
                {isLoading ? (
                  <Square size={16} fill="currentColor" />
                ) : (
                  <Send size={16} className="ml-0.5" />
                )}
              </button>
            </div>
          </form>
          <div className="text-center mt-3 text-xs text-gray-500">
            Agent output is generated by AI and may be inaccurate.
          </div>
        </div>
      </div>
    </div>
  );
};